version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: moustasweb
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://root:root@mongodb:27017/moustasweb?authSource=admin"

  frontend:
    image: httpd:2.4
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"

volumes:
  mongodb_data:
