name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Analyse complète du code source

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ben-sliman
            -Dsonar.projectKey=ben-sliman_moustasweb
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=backend,frontend
            -Dsonar.exclusions=node_modules/**,dist/**,build/**,backend/test/**,frontend/test/**
            -Dsonar.tests=backend/test,frontend/test
            -Dsonar.test.inclusions=backend/test/**/*.test.js,frontend/test/**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sourceEncoding=UTF-8

  build:
    needs: sonarcloud
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build backend Docker image
        working-directory: backend
        run: docker build -t my-app-backend .

      - name: Build frontend Docker image (copie des fichiers statiques)
        working-directory: frontend
        run: docker build -t my-app-frontend .

      - name: Push Docker images to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app-backend my-docker-user/my-app-backend:latest
          docker tag my-app-frontend my-docker-user/my-app-frontend:latest
          docker push my-docker-user/my-app-backend:latest
          docker push my-docker-user/my-app-frontend:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull my-docker-user/my-app-backend:latest
            docker pull my-docker-user/my-app-frontend:latest
            docker stop my-app-backend || true
            docker stop my-app-frontend || true
            docker rm my-app-backend || true
            docker rm my-app-frontend || true
            docker run -d -p 3000:3000 --name my-app-backend my-docker-user/my-app-backend:latest
            docker run -d -p 80:80 --name my-app-frontend my-docker-user/my-app-frontend:latest
